name: "test coverage"
on: push

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install dependencies
      run: npm ci

    - name: run tests and instrument coverage
      run: make test-coverage

    - name: publish code coverage to code-climate (duh)
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 3470adaf12ff7cecdfe5a968ae0e95d098b6ee58c340114e1e90d440ee9e66ab
